### ISSUE TITLE
Why is my charger only charging with 5A?

### ISSUE THREAD

**Issue by DennisM12** [cdragon/TWCManager#12]
Dear,

My setup is almost working but I can't get more than 5A out of the charger. When I select 13A for example I get 13A available but nothing changes and the car keeps charging on just 5A (I can stop and start the charging process so I have communication) but I want to charge the car faster and its possible hardware wise. I have 'wiringMaxAmpsAllTWCs' at 40 so that shouldnt be an issue. Anyone knows how to solve this ?

Thanks in advance.

Best regards,

Dennis

**Comment by robot256** [comment]
I don't think it's an issue with this project, but I had the same thing happen to my Model 3.  After a few hours of having my home automation system adjust the TWC power and turning the car on and off, the car's internal amp limit got stuck at 6 no matter what the TWC did.  I had to replug the connector to reset it.  Manually changing the limit might have worked to.  Seems like it's a bug and/or feature in the car software.  I'm working on a solar power tracking algorithm that involves fewer commands sent to the car to see if that helps.

**Comment by DennisM12** [comment]
> I don't think it's an issue with this project, but I had the same thing happen to my Model 3. After a few hours of having my home automation system adjust the TWC power and turning the car on and off, the car's internal amp limit got stuck at 6 no matter what the TWC did. I had to replug the connector to reset it. Manually changing the limit might have worked to. Seems like it's a bug and/or feature in the car software. I'm working on a solar power tracking algorithm that involves fewer commands sent to the car to see if that helps.

Allready fixed!

**Comment by robot256** [comment]
> Allready fixed!

May I ask what you did to fix it, or how you determined it is or is not the fault of TWCManager?  I'm still having this issue with the latest code from the repository.

**Comment by deece** [comment]
> > Allready fixed!
> 
> May I ask what you did to fix it, or how you determined it is or is not the fault of TWCManager? I'm still having this issue with the latest code from the repository.

Are you limiting the charge current in-car?
